PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 0
ULTIMATE_VERSION_TAG := FifTeen

CURRENT_DEVICE=$(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)

ULTIMATE_BUILDTYPE := UNOFFICIAL

ifeq ($(ULTIMATE_OFFICIAL), true)
     ULTIMATE_BUILDTYPE := OFFICIAL
endif

ULTIMATE_VERSION := UltimateOS-$(ULTIMATE_VERSION_TAG)-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CURRENT_DEVICE)-$(ULTIMATE_BUILDTYPE)-$(shell date -u +%Y%m%d-%H%M)

ULTIMATE_DISPLAY_VERSION := $(ULTIMATE_VERSION_TAG)-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.ultimate.version=$(ULTIMATE_VERSION) \
    ro.ultimate.releasetype=$(ULTIMATE_BUILDTYPE) \
    ro.ultimate.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.modversion=$(ULTIMATE_VERSION) \
    ro.ultimate.display.version=$(ULTIMATE_DISPLAY_VERSION)

# Signing
-include vendor/ultimate-priv/keys.mk